name: Deploy to Yandex Object Storage (contacts)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: AWS CLI
        uses: aws-actions/setup-cli@v2

      - name: Upload static assets (immutable)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
        run: |
          aws s3 sync ./dist "s3://${AWS_S3_BUCKET}/" \
            --endpoint-url "https://storage.yandexcloud.net" \
            --exclude "*.html" \
            --cache-control "public, max-age=31536000, immutable" \
            --acl public-read \
            --delete

      - name: Upload HTML (no-cache)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
        run: |
          aws s3 sync ./dist "s3://${AWS_S3_BUCKET}/" \
            --endpoint-url "https://storage.yandexcloud.net" \
            --exclude "*" --include "*.html" \
            --cache-control "no-cache, no-store, must-revalidate" \
            --acl public-read
